import { Actor, HttpAgent } from '@dfinity/agent';
import type { backendInterface } from '../backend';

// Get canister ID from environment or env.json
function getCanisterId(): string {
  // Try environment variables first (set by build process)
  if (typeof process !== 'undefined' && process.env) {
    const envCanisterId = 
      process.env.CANISTER_ID_BACKEND ||
      process.env.BACKEND_CANISTER_ID;
    if (envCanisterId) {
      return envCanisterId;
    }
  }

  // Try to load from env.json (deployed apps)
  try {
    // @ts-ignore - env.json is generated at build time
    const envJson = window.__ENV__;
    if (envJson?.CANISTER_ID_BACKEND) {
      return envJson.CANISTER_ID_BACKEND;
    }
  } catch (e) {
    // env.json not available
  }

  // Fallback: try to extract from current URL (for ic0.app/icp0.io domains)
  const hostname = window.location.hostname;
  const icDomainMatch = hostname.match(/^([a-z0-9-]+)\.(ic0\.app|icp0\.io|localhost)$/);
  if (icDomainMatch) {
    return icDomainMatch[1];
  }

  throw new Error('Backend canister ID not found. Please ensure the canister is deployed and environment is configured correctly.');
}

// Get agent host based on environment
function getAgentHost(): string {
  // Check if we're in local development
  if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    return `http://${window.location.hostname}:4943`;
  }

  // Production: use IC mainnet gateway
  return 'https://icp-api.io';
}

export interface ActorOptions {
  agentOptions?: {
    identity?: any;
    host?: string;
  };
}

// Cache for idlFactory to avoid repeated dynamic imports
let idlFactoryCache: any = null;

async function loadIdlFactory(): Promise<any> {
  if (idlFactoryCache) {
    return idlFactoryCache;
  }

  try {
    // Dynamic import at runtime - the declarations are generated by dfx generate
    const declarationsPath = '../declarations/backend/index.js';
    const module = await import(declarationsPath);
    idlFactoryCache = module.idlFactory;
    return idlFactoryCache;
  } catch (error) {
    console.error('Failed to load backend declarations:', error);
    throw new Error(
      'Backend declarations not found. Please ensure the canister is deployed and declarations are generated (run "dfx generate backend").'
    );
  }
}

export async function createActorWithConfig(options?: ActorOptions): Promise<backendInterface> {
  const canisterId = getCanisterId();
  const host = options?.agentOptions?.host || getAgentHost();
  const idlFactory = await loadIdlFactory();

  const agent = new HttpAgent({
    host,
    ...options?.agentOptions,
  });

  // Fetch root key for certificate validation during local development
  if (host.includes('localhost') || host.includes('127.0.0.1')) {
    try {
      await agent.fetchRootKey();
    } catch (err) {
      console.warn('Unable to fetch root key. Check to ensure that your local replica is running');
      console.error(err);
    }
  }

  // Create and return the actor
  return Actor.createActor<backendInterface>(idlFactory, {
    agent,
    canisterId,
  });
}

export function getConnectionInfo(): { host: string; canisterId: string | null } {
  try {
    const canisterId = getCanisterId();
    const host = getAgentHost();
    return { host, canisterId };
  } catch (e) {
    return { host: getAgentHost(), canisterId: null };
  }
}
