/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ListAllQuizzesResult = [QuizId, Array<QuizId>];
export interface Question {
  'answers' : Array<string>,
  'text' : string,
  'correctAnswer' : bigint,
}
export type QuizId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'appendQuestions' : ActorMethod<[QuizId, Array<Question>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBlockNames' : ActorMethod<[QuizId], Array<[bigint, string]>>,
  'getAllQuestions' : ActorMethod<[QuizId], Array<Question>>,
  'getBlockName' : ActorMethod<[QuizId, bigint], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestion' : ActorMethod<[QuizId, bigint], [] | [Question]>,
  'getQuestionCount' : ActorMethod<[QuizId], bigint>,
  'getQuestions' : ActorMethod<[QuizId, bigint, bigint], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllQuizzes' : ActorMethod<[], ListAllQuizzesResult>,
  'renameQuiz' : ActorMethod<[QuizId, QuizId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuestions' : ActorMethod<[QuizId, Array<Question>], undefined>,
  'setBlockName' : ActorMethod<[QuizId, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];