/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizId = IDL.Text;
export const Question = IDL.Record({
  'answers' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ListAllQuizzesResult = IDL.Tuple(QuizId, IDL.Vec(QuizId));

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'appendQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBlockNames' : IDL.Func(
      [QuizId],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func([QuizId], [IDL.Vec(Question)], ['query']),
  'getBlockName' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestion' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getQuestionCount' : IDL.Func([QuizId], [IDL.Nat], ['query']),
  'getQuestions' : IDL.Func(
      [QuizId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllQuizzes' : IDL.Func([], [ListAllQuizzesResult], ['query']),
  'renameQuiz' : IDL.Func([QuizId, QuizId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
  'setBlockName' : IDL.Func([QuizId, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizId = IDL.Text;
  const Question = IDL.Record({
    'answers' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ListAllQuizzesResult = IDL.Tuple(QuizId, IDL.Vec(QuizId));
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'appendQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBlockNames' : IDL.Func(
        [QuizId],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([QuizId], [IDL.Vec(Question)], ['query']),
    'getBlockName' : IDL.Func(
        [QuizId, IDL.Nat],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestion' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getQuestionCount' : IDL.Func([QuizId], [IDL.Nat], ['query']),
    'getQuestions' : IDL.Func(
        [QuizId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllQuizzes' : IDL.Func([], [ListAllQuizzesResult], ['query']),
    'renameQuiz' : IDL.Func([QuizId, QuizId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
    'setBlockName' : IDL.Func([QuizId, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };