/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article { 'title' : string, 'content' : string }
export type ExternalBlob = Uint8Array;
export interface HealthCheckResult {
  'backendVersion' : bigint,
  'systemTime' : bigint,
}
export interface Question {
  'answers' : Array<string>,
  'hint' : [] | [string],
  'text' : string,
  'correctAnswer' : bigint,
  'imageUrl' : [] | [ExternalBlob],
}
export type QuizId = string;
export interface StateSnapshot {
  'blockNames' : Array<[string, Array<[bigint, string]>]>,
  'version' : bigint,
  'questions' : Array<[string, Array<Question>]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'appendQuestions' : ActorMethod<[QuizId, Array<Question>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportAllState' : ActorMethod<[], StateSnapshot>,
  'generateArticle' : ActorMethod<[string], Article>,
  'getAllBlockNames' : ActorMethod<[QuizId], Array<[bigint, string]>>,
  'getAllQuestions' : ActorMethod<[QuizId], Array<Question>>,
  'getArticle' : ActorMethod<[string], Article>,
  'getBlockName' : ActorMethod<[QuizId, bigint], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestion' : ActorMethod<[QuizId, bigint], [] | [Question]>,
  'getQuestionCount' : ActorMethod<[QuizId], bigint>,
  'getQuestions' : ActorMethod<[QuizId, bigint, bigint], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminRole' : ActorMethod<[], boolean>,
  'healthCheck' : ActorMethod<[], HealthCheckResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isValidQuizId' : ActorMethod<[QuizId], boolean>,
  'listAllQuizzes' : ActorMethod<[], Array<QuizId>>,
  'pushAllArticlesToBackend' : ActorMethod<[], undefined>,
  'pushArticlesToContentTeam' : ActorMethod<[], undefined>,
  'renameQuiz' : ActorMethod<[QuizId, QuizId], undefined>,
  'restoreState' : ActorMethod<[StateSnapshot], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuestions' : ActorMethod<[QuizId, Array<Question>], undefined>,
  'setBlockName' : ActorMethod<[QuizId, bigint, string], undefined>,
  'writeArticle' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];