/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const QuizId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Question = IDL.Record({
  'answers' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'imageUrl' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StateSnapshot = IDL.Record({
  'blockNames' : IDL.Vec(
    IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)))
  ),
  'version' : IDL.Nat,
  'questions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Question))),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HealthCheckResult = IDL.Record({
  'backendVersion' : IDL.Nat,
  'systemTime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'appendQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'exportAllState' : IDL.Func([], [StateSnapshot], []),
  'getAllBlockNames' : IDL.Func(
      [QuizId],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func([QuizId], [IDL.Vec(Question)], ['query']),
  'getBlockName' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestion' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getQuestionCount' : IDL.Func([QuizId], [IDL.Nat], ['query']),
  'getQuestions' : IDL.Func(
      [QuizId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminRole' : IDL.Func([], [IDL.Bool], ['query']),
  'healthCheck' : IDL.Func([], [HealthCheckResult], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidQuizId' : IDL.Func([QuizId], [IDL.Bool], ['query']),
  'listAllQuizzes' : IDL.Func([], [IDL.Vec(QuizId)], ['query']),
  'renameQuiz' : IDL.Func([QuizId, QuizId], [], []),
  'restoreState' : IDL.Func([StateSnapshot], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
  'setBlockName' : IDL.Func([QuizId, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const QuizId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Question = IDL.Record({
    'answers' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'imageUrl' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StateSnapshot = IDL.Record({
    'blockNames' : IDL.Vec(
      IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)))
    ),
    'version' : IDL.Nat,
    'questions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Question))),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HealthCheckResult = IDL.Record({
    'backendVersion' : IDL.Nat,
    'systemTime' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'appendQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'exportAllState' : IDL.Func([], [StateSnapshot], []),
    'getAllBlockNames' : IDL.Func(
        [QuizId],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([QuizId], [IDL.Vec(Question)], ['query']),
    'getBlockName' : IDL.Func(
        [QuizId, IDL.Nat],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestion' : IDL.Func([QuizId, IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getQuestionCount' : IDL.Func([QuizId], [IDL.Nat], ['query']),
    'getQuestions' : IDL.Func(
        [QuizId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminRole' : IDL.Func([], [IDL.Bool], ['query']),
    'healthCheck' : IDL.Func([], [HealthCheckResult], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidQuizId' : IDL.Func([QuizId], [IDL.Bool], ['query']),
    'listAllQuizzes' : IDL.Func([], [IDL.Vec(QuizId)], ['query']),
    'renameQuiz' : IDL.Func([QuizId, QuizId], [], []),
    'restoreState' : IDL.Func([StateSnapshot], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQuestions' : IDL.Func([QuizId, IDL.Vec(Question)], [], []),
    'setBlockName' : IDL.Func([QuizId, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };